version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=likesApi

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/likesApi?sslmode=disable
    depends_on:
      - postgres
      - redis 
    entrypoint:
      [
        "/bin/sh",
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/bin/sh",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
