// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Content struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Like struct {
	UserID    int64        `json:"user_id"`
	ContentID int64        `json:"content_id"`
	Liked     sql.NullBool `json:"liked"`
	UpdateAt  time.Time    `json:"update_at"`
}

type Notification struct {
	UserID int64 `json:"user_id"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
